

services:

  web:

    build: .

    ports:
      - "5000:5000"

    depends_on:
      - mysql

    restart: always

  mysql:

    image: mysql:8.0

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: root123

      MYSQL_DATABASE: portfolio_db

      MYSQL_USER: siddhi

      MYSQL_PASSWORD: siddhi123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:

  mysql_data: